dtserver:
  container_name: "dtserver"
  hostname: "docker-dtserver"
  image: "dynatrace/server:6.5-slim"
  environment:
    DT_SERVER_NAME: "dtserver"
    DT_SERVER_LICENSE_KEY_FILE_URL: "${DT_SERVER_LICENSE_KEY_FILE_URL}"
    HOST_NAME: "docker-dtserver"
  ports:
    - "2020:2020" # Dynatrace Clients (TCP)
    - "2021:2021" # Dynatrace Clients (TCP with SSL)
    - "8020:8020" # Dynatrace Web Server (HTTP)
    - "8021:8021" # Dynatrace Web Server (HTTPS)
    - "9911:9911" # Dynatrace Web UI (HTTPS)
    - "9998:9998" # Dynatrace Agents (TCP)
  volumes:
    - "/tmp/log/dynatrace/servers/dtserver:/dynatrace/log/server/dtserver"

dtcollector:
  container_name: "dtcollector"
  hostname: "docker-dtcollector"
  image: "dynatrace/collector:6.5-slim"
  links:
    - dtserver
  environment:
    DT_COLLECTOR_NAME: "dtcollector"
    HOST_NAME: "docker-dtcollector"
    DT_COLLECTOR_GROUP_NAME: "docker-collectors"
  volumes:
    - "/tmp/log/dynatrace/collectors/dtcollector:/dynatrace/log/collector/dtcollector"

dtagent:
  container_name: "dtagent"
  hostname: "docker-dtagent"
  image: "dynatrace/agent:6.5-slim"
  environment: 
    DT_AGENT_NAME: "tomcat_Konakart"
  volumes:
    - /dynatrace
    - "/tmp/log/dynatrace/agents/dtagent:/dynatrace/log/agent"
