version: '2'

services:
    app:
        image: braydenneale/konakart:1.0.0
        env_file:
            - ./app/konakart.env
        depends_on:
            - database

    database:
        image: mysql:latest
        env_file:
            - ./app/mysql.env
        ports:
            - 3306:3306

    proxy:
        image: dockercloud/haproxy:latest
        ports:
            - 80:80
        links:
            - app
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
