version: '2'

volumes:
    db-data:
        external: false
            
services:
    app:
        build: ./app
        env_file:
            - ./app/konakart.env
        depends_on:
            - db

    database:
        image: mysql:latest
        env_file:
            - ./app/konakart.env
        ports:
            - 3306:3306

    proxy:
        image: dockercloud/haproxy:latest
        ports:
            - 80:80
        links:
            - konakart_app
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
