konakart_app:
    build: ./app
    env_file:
        - ./app/konakart.env
    volumes_from:
        - dtagent
    external_links:
        - dtcollector
    #command:
    #    - /usr/local/konakart/bin/catalina.sh run

konakart_db:
    image: beantoast/dtkonakart_mysql
    ports:
        - 3306:3306

konakart_proxy:
    image: dockercloud/haproxy:latest
    ports:
        - 80:80
    links:
        - konakart_app
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
