apiVersion: v1
kind: ReplicationController
metadata:
    name: konakart-master
    labels:
        app: konakart
        role: master
        tier: web
spec:
    replicas: 1

    template:
        metadata:
            labels:
                app: konakart
                role: master
                tier: backend
        spec:
            containers:
                - name: master
                image: braydenneale/konakart:1.0.0
                resources: 
                requests:
                    cpu: 100m
                    memory: 100Mi
                ports:
                    - containerPort: 8780
