apiVersion: v1
kind: Service
metadata:
    name: konakart-master
    labels:
        app: konakart
        role: master
        tier: web
spec:
    ports:
        - port: 8780
        targetPort: 8780
    selector:
        app: konakart
        role: master
        tier: web
