apiVersion: v1
kind: ReplicationController
metadata:
    name: konakart_web
    labels:
        app: konakart
        tier: web
spec:
    replicas: 1

    template:
        metadata:
            labels:
                app: konakart
                tier: web
        spec:
            containers:
                -name: konakart_web
                image: braydenneale/konakart:1.0.0
                resources:
                requests:
                    cpu: 100m
                    memory: 100Mi
                ports:
                    -containerPort: 8780
---
apiVersion: v1
kind: Service
metadata:
    name: konakart_web
    labels:
        app: konakart
        tier: web
spec:
    ports:
        - port: 8780
          targetPort: 8780
    selector:
        app: konakart
        tier: web
